version: '3.8'

services:
  # Backend (NestJS)
  api:
    build: ./agenda-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  # Frontend (Next.js)
  frontend:
    build: ./agenda-front
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - api

  # Banco de dados PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volume para persistir os dados do PostgreSQL
volumes:
  postgres_data:
